#first seen at https://github.com/darkraiden/ansible-role-pip
# bootstrap installs python2 pip - the latest version

---
- name: Bootstrap pip
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_dest }}"

- name: Install pip for python2
  command: "{{ pip_command_python }} {{ pip_download_dest }}/{{ pip_download_filename }}"
  become: "yes"

- name: Install pip for python3
  command: "{{ pip_command_python3 }} {{ pip_download_dest }}/{{ pip_download_filename }}"
  become: "yes"

- name: Delete downloaded file
  file:
    path: "{{ pip_download_dest }}/{{ pip_download_filename }}"
    state: absent
