#first seen at https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933
# Installs the latest docker-ce
# I replaced {{ansible_distribution_release}} with xenial
---

- name:  "Add Docker APT repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: "present"
  become: "yes"

- name:  "Install Docker"
  apt:  name=docker-ce
  become: "yes"
