#first seen here: http://www.snip2code.com/Snippet/63701/Ansible-task-to-install-nvm-and-node
# then seen at: https://gist.github.com/komuw/b3b5d24977d4df7bd549
# Here is how to install nvm and node in an Ansible task.
# I tried a bunch of different things, and as usual it's simple, but you have to get it right.
# The important part is that you have to shell with /bin/bash -c and source nvm.sh
---

- stat: "path={{ user_dir }}/.nvm/nvm.sh"
  register: "check_nvmdir"

- name: Download for the nvm install
  get_url:
    mode: "u+rwx"
    url: "{{ nvm_download_url }}"
    dest: "/tmp/{{ nvm_download_filename }}"
  when: "check_nvmdir.stat.exists == False"

- name: Install node version manager
  command: "sh /tmp/{{ nvm_download_filename }}"
  when: "check_nvmdir.stat.exists == False"

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ nvm_node_version }} && nvm alias default {{ nvm_node_version }}" 
    creates={{ user_dir }}/.nvm/alias
