---
- include: "apt.yml"
- include: "get_pip.yml"
- include: "pip_install.yml"
- include: "get_jupyter_notebook.yml"
- include: "get_nvm.yml"
- include: "get_docker.yml"
- include: "get_atom.yml"
- include: "get_android_studio.yml"
- include: "get_ms_code.yml"
- include: "system.yml"
