---
- name: "Install standard python 2 packages"
  pip:
    name: ['virtualenv']
    state: present
  become: "yes"
  register: echo

- name: "Install standard python 3 packages"
  pip:
    executable: pip3
    name: ['pep8', 'pylint']
    state: present
  become: "yes"
  register: echo
