---
- name: "Install standard python 2 packages"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv
  become: "yes"
  register: echo

- name: "Install standard python 3 packages"
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
    - pep8
    - pylint
  become: "yes"
  register: echo
