#!/bin/sh

# A bash script that acts like pip3
# for Mint 19 - using the Python3 pip

# Save current directory
APPDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Find the calling programs directory
CALLIING_DIR="/proc/$PPID/cwd"
echo Calling Dir: "${CALLING_DIR}"

cd "$CALLING_DIR"

python3 -m pip "$@"

cd "$APPDIR"
